# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1d4a9570db5057ccc7828ed0a6aed0d8a936b60e6a6e9f74daa21d852903437f54f21017c771267ebeab4a0d5a40a9eb6e1c733986330d5aa6c90d41a9f0c66

test:
  secret_key_base: 1c0158ad04aee5afac353abb5d2e7f341ad45a7c9df23bd95a13eff839f19c72e6381355ad397826f5f8155e4055b88df0e4983a8df059a7ec78afd60151fc7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
