# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c907142d2d00c2eb9dde7415f806f90332011fea6218f4205df64f1ce5a6e75d78c5c5e39612c1341a343e49b2c638708ed8fa8df3cbd27bc54b663db54fe3ad

test:
  secret_key_base: a7b232647ffcaf88ee46986f192ad6e1b12fce1f1d695274ce0747dc3ebd4aac02d7709ec90b0c6f66db02f922cc89d89b38e8ee94101f33db38dd37e1f704c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
