# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 298167c14ddd50a4ca9d11db36916f37372b7754d18ee516fea0c8e9b14fd2025bcc9005da3f268996887b1baa5239bee2f471c3da0555e9a0134eb3ca0224c3

test:
  secret_key_base: 340e09c6c947a36367f0414ec028d732e3f8c6fe14266e2b7df1f7a3c83d24cf5122ed51f010cfbf1537f468406b2260b0f8e4d1d3ec02321a90c12a75cb1e7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
