# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8b97e9e1015c5d43c3a4b875c172fc6645f96c3934d085db6e4fb4e011d188478acae183bd5d6c1303f5fbd29d1f453dbf7e0a96b51addeabb6d27c6ef5ef5a

test:
  secret_key_base: 944286e2259396bd0c6796bbca4f0c1b75d095e314ed478188990022dbb1c6bcbde47ffcce142cc1714b4c9804b5a4bb63383674884e92cadd9d62a861d6f3c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
