# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 156db253435a89b4f7163e589c9d2f8b728388a2c779c808a94a28090f4c14bede16585701037e1f418f320fa4eac52b8cb17c8d35a1f5113667896913ad7816

test:
  secret_key_base: 348f2f7aa2367d6cdd6be4de4541153e333fb81fbb7b91a874be249c91ae1f23aace13910ebd8a0202e8623fd2e91acf7143f4c98b5077309bc517fde0581448

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
