# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b342243cad430dc0843a4bac4443f286f9afa086cbaad6c4e45a8e6563964e19816ee879a320d06ddbabf472b26a647d0952f9b49057c379b4827bad9d8f90c4

test:
  secret_key_base: 5b9b91e3be765b5e4da927df8a1524dfd642895f1ff457f7aed4fe1865a5f602ae30773fd377e86fbf599c6e77f34a31b45a59c39af88b5cce28e508d911ce7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
