# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30b4d9ade8251abcfe6fb0aec89d78d10d8f27f5bbd3543944ba84a9ad409ecc0a126b7aab69638508a60f1fcaf8b102535c64d921bfbfdc37d0fdaa4dfa1a17

test:
  secret_key_base: a63c2f59cd7e5d950b227591388c14b0c17f2dee640d89e23590426aba9220de507f0fcd6aac6a09825d44fc2ed5b1124f5df7265c9e977afecde984420c89f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
