# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 235821a26294f851f1bfd41b65008601423a21ea426653d851dbb1c71b6c3987c2a7bcfa5f58617dec56c9c5ad6a811fa7759e8d62802183f310c0b704db9b57

test:
  secret_key_base: 960ba5a661248fc03eb5e8e117a9f7fd0629576fcc9adcc0e1cc0927f9c67241af5c983107a17a03602fa458a533764f395ec1c0a923d0124d727cdfb3383fc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
