# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b17ce0559393c19cea9900aa0fdf26726f95b5d23832fd39b14858874334c436e1fabcdf9218e5741e9a3459ad5e178357784e868b3613c70731675a36241497

test:
  secret_key_base: a270303b7eef66a4ea202de302a7d62e3697f3c554529830d210c4f5a9530ee9830d2c34e6ce00dc648e49e90f20dd30966f9505a8748f554b51f7eb95e1d227

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
