# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da8c7c401311ab9b875c7e96e3411a872605ca4fa78da7f2bea2907ea9b9a91dc75a035e74b9f8c49bc6cd6585922b66b3334853ae6f3b154a027b3376205500

test:
  secret_key_base: 0c30ee68ea4f8cf00ba171974285244494883b49a1ad87be70fdc706aa0b2ae5d49b01f2c6cba4df4c0c307f75da305b5294de6ce7c523a3ecb4a0eb894cc7f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
