# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba9c15b5deba4e9617f6224cade40b00d3cf1573349aad043e4ee307312d0891967a489eb570c1446d9aefbea104b21e0de59b67ea4a9170d47c300e00cf13b7

test:
  secret_key_base: 8455e04feba995be58cbfeb167736a101e0531a11a29075bbec78f12db4869048377c65e76ff34838c212f419564d05241da2e535d13357d302a67fbcedcbf85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
